# Generated by Django 6.0.4 on 2026-05-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('emoji', models.CharField(default='🍽️', max_length=10)),
                ('calificacion', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('tiempo_entrega', models.CharField(default='25-35 min', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
