# Generated by Django 6.0.4 on 2026-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='local',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='local',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='local',
            name='tiempo_entrega',
        ),
        migrations.AddField(
            model_name='local',
            name='comuna',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Providencia', 'Providencia'), ('Maipú', 'Maipú'), ('Puente Alto', 'Puente Alto'), ('Viña del Mar', 'Viña del Mar'), ('Valparaíso', 'Valparaíso')], default='Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='local',
            name='direccion',
            field=models.CharField(default='Sindirección', max_length=200),
        ),
        migrations.AddField(
            model_name='local',
            name='menu',
            field=models.TextField(default='Menú no disponible'),
        ),
        migrations.AddField(
            model_name='local',
            name='region',
            field=models.CharField(choices=[('RM', 'Región Metropolitana'), ('V', 'Valparaíso'), ('VI', 'O’Higgins'), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía')], default='RM', max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(choices=[('completos', 'Completos'), ('hamburguesas', 'Hamburguesas'), ('pizzas', 'Pizzas'), ('sushi', 'Sushi'), ('postres', 'Postres')], default='hamburguesas', max_length=50),
        ),
    ]
