# Generated by Django 6.0.4 on 2026-05-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_local_calificacion_remove_local_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='local',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='local',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='local',
            name='region',
        ),
        migrations.AddField(
            model_name='local',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='locales/'),
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(choices=[('completos', 'Completos'), ('hamburguesas', 'Hamburguesas'), ('pizzas', 'Pizzas'), ('sushi', 'Sushi'), ('postres', 'Postres')], max_length=50),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Región Metropolitana'), ('V', 'Valparaíso'), ('VI', 'O’Higgins'), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía')], default='RM', max_length=50)),
                ('comuna', models.CharField(choices=[('Santiago', 'Santiago'), ('Providencia', 'Providencia'), ('Maipú', 'Maipú'), ('Puente Alto', 'Puente Alto'), ('Valparaíso', 'Valparaíso'), ('Viña del Mar', 'Viña del Mar'), ('Rancagua', 'Rancagua'), ('Talca', 'Talca'), ('Concepción', 'Concepción'), ('Temuco', 'Temuco')], default='Santiago', max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.local')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.sucursal')),
            ],
        ),
    ]
